icsApp/urls.py
from django.conf.urls import url
from . import views

app_name = "icsApp"

urlpatterns = [
    url(r'^inventory/$', views.inventory_list, name='inventory_list'),
    url(r'^test_search_results/$', views.search, name='search'), # <- url for searchresults
    url(r'^inventory/(?P<pk>\d+)/quantity/increase/$', views.quantity_increase, name='quantity_increase'),
    url(r'^inventory/(?P<pk>\d+)/quantity/decrease/$', views.quantity_decrease, name='quantity_decrease'),
    url(r'^inventory/(?P<pk>\d+)/edit/$', views.inventory_edit, name='inventory_edit'),
    url(r'^inventory/(?P<pk>\d+)/delete/$', views.inventory_delete, name='inventory_delete'),
    url(r'^inventory/create/$', views.inventory_new, name='inventory_new'),
    url(r'^inventory/import/$', views.import_data, name='import_data'),
    url(r'^inventory/export/$', views.export_data, name='export_data'),
    url(r'^inventory/sortAsc-itemN$', views.ascending_item, name='ascending_item'),
    url(r'^inventory/sortDsc-itemN$', views.descending_item, name='descending_item'),
    url(r'^inventory/sortAsc-ctgry$', views.ascending_category, name='ascending_category'),
    url(r'^inventory/sortDesc-ctgry$', views.descending_category, name='descending_category'),
    url(r'^inventory/sortAsc-vndr$', views.ascending_vendor, name='ascending_vendor'),
    url(r'^inventory/sortDesc-vndr$', views.descending_vendor, name='descending_vendor'),
]

icsSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('icsApp.urls', namespace='icsApp')),
]

icsApp/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Inventory(models.Model):
    item_name = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField(null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    item_position = models.CharField(max_length=50, null=True, blank=True)
    category = models.CharField(max_length=50, null=True, blank=True)
    vendor = models.CharField(max_length=50, null=True, blank=True)
    vendor_id = models.CharField(max_length=20, null=True, blank=True)
    link = models.CharField(max_length=100, null=True, blank=True )
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    updated_date = models.DateField(default=datetime.date.today())

    def updated(self):
        self.updated_date = datetime.date.today()
        self.save()

    def __str__(self):
        return str(self.item_name)

    def total_values(self):
        return self.unit_price * self.quantity

icsApp/forms.py
from django import forms
from .models import Inventory

class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = (
            'item_name', 'quantity', 'location', 'item_position', 'category', 'vendor', 'vendor_id',
            'link', 'unit_price')

class UploadFileForm(forms.Form):
    file = forms.FileField()

icsApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *
from django.http import HttpResponseRedirect, HttpResponse
import datetime

# Create your views here.

# Import from Excel
class Customer:
    def __init__(self, item_name,
                 quantity, location,
                 item_position, category,
                 vendor, link, unit_price, updated_date):
        self.itemName = item_name
        self.quantity = quantity
        self.location = location
        self.itemPosition = item_position
        self.category = category
        self.vendor = vendor
        self.link = link
        self.unitPrice = unit_price
        # self.updatedDate = updated_date

import csv
import easygui
import sys

def import_data(request):

        filename = easygui.fileopenbox()
        with open(filename, "r", newline='') as file:
            reader = csv.reader(file)

            # read each row of the data
            for row in reader:
                if row[0] == "QTY": # skip first line
                    continue

                # create a list of Inventory objects
                obj, created = Inventory.objects.get_or_create(
                    item_name = row[1],
                    quantity = row[0],
                    # location = row[2],
                    # item_position = row[3],
                    # category = row[4],
                    vendor = row[2],
                    vendor_id = row[3],
                    link = row[4],
                    unit_price = row[5]
                    # updated_date = row[9]
                )
            return HttpResponseRedirect("/inventory/")


# List inventory items
def inventory_list(request):
    inventory = Inventory.objects.order_by('-updated_date')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

#sort by item
def ascending_item(request):
    inventory = Inventory.objects.order_by('item_name')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

def descending_item(request):
    inventory = Inventory.objects.order_by('-item_name')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

#sort by category
def ascending_category(request):
    inventory = Inventory.objects.order_by('category')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

def descending_category(request):
    inventory = Inventory.objects.order_by('-category')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

#sort by vendor
def ascending_vendor(request):
    inventory = Inventory.objects.order_by('vendor')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

def descending_vendor(request):
    inventory = Inventory.objects.order_by('-vendor')
    return render(request, 'inventory_list.html', {'inventorys': inventory})

# Add Inventory item
def inventory_new(request):
    if request.method == "POST":
        form = InventoryForm(request.POST)
        if form.is_valid():
            inventory = form.save(commit=False)
            inventory.updated_date = datetime.date.today()
            inventory.save() #saves the values
            return HttpResponseRedirect("/inventory/")
    else:
        form = InventoryForm()
    return render(request, 'inventory_new.html', {'form': form})

# Edit inventory item
def inventory_edit(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    if request.method == "POST":
        form = InventoryForm(request.POST, instance=inventory)
        if form.is_valid():
            inventory.updated_date = datetime.date.today()
            inventory = form.save()
            inventory.save()
            return HttpResponseRedirect("/inventory/")
    else:
        form = InventoryForm(instance=inventory)
    return render(request, 'inventory_edit.html', {'form': form})

# Delete Inventory item
def inventory_delete(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    inventory.delete()
    return HttpResponseRedirect("/inventory/")

def quantity_increase(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    inventory.quantity = inventory.quantity + 1
    inventory.save()
    return HttpResponseRedirect("/inventory/")

def quantity_decrease(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    inventory.quantity = inventory.quantity - 1
    inventory.save()
    return HttpResponseRedirect("/inventory/")

def search(request):
    query = request.POST['usr_query']
    inventory = Inventory.objects.filter(item_name__contains=query)
    return render(request, 'inventory_list.html', {'inventorys': inventory})


def export_data(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="new.csv"'
    writer = csv.writer(response)
    writer.writerow(['item_name', 'quantity', 'location', 'Item Position', 'category', 'vendor', 'link', 'Unit Price', 'Updated Date'])
    records = Inventory.objects.all()

    for record in records:
        arr = []
        arr.append(record.item_name)
        arr.append(record.quantity)
        arr.append(record.location)
        arr.append(record.item_position)
        arr.append(record.category)
        arr.append(record.vendor)
        arr.append(record.link)
        arr.append(record.unit_price)
        arr.append(record.updated_date)
        writer.writerow(arr)
    return response

icsApp/templates/inventory_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Inventory</title>
</head>
<body>
    <h1>Edit Inventory</h1>
    <form method="POST" class="inventory-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
</body>
</html>

icsApp/templates/inventory_list.html
{% load staticfiles %}
	<!DOCTYPE html>
	<html>
	<head>
		<title>Inventory List</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	</head>
	<style>
		body {
			background-color: beige;
		}
        h2 {
            margin: 0;
            display: inline-block;
        }
        .button {
        float: right;
        justify-content:flex-end;
        align-items:center;
        }
        .rbutton {
        background-color: #e6e6fa;
        color: black;
        display: inline-block;
        padding: 5px;
        text-align: center;
        font-size: 14px;
        border-radius: 20%;
        }
        .triangle-up {
			width: 0;
			height: 0;
			border-left: 5px solid transparent;
			border-right: 5px solid transparent;
			border-bottom: 5px solid #555;
		}
		.triangle-down {
			width: 0;
			height: 0;
			border-left: 5px solid transparent;
			border-right: 5px solid transparent;
			border-top: 5px solid #555;
		}

        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
        img.resize {
            max-width:50%;
            max-height:50%;
        }
        p {
        	position: relative;
			left: -10px;
        }
        h2.align {
			text-align: center;
			display: inline-block;
		}
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }

	</style>
	<body>

	<nav class="navbar navbar-inverse">

            <a href="/inventory/">
                <img src="{% static "images/BRB.gif" %}" width="200" height="60" alt="customer" align = "middle">
		    </a>
		<h2 style = "align:center; vertical-align:middle; padding-left:650px"><font color="silver">Welcome to Biomechanics Inventory Control System!</font></h2>

	</nav>
	<div class="container" style="padding-top: 50px">
	<form class="search" action="{% url 'icsApp:search' %}" method='post'>
	  {% csrf_token %}
	  <input type="search" placeholder="Search item here..." name="usr_query"
		  value='{{ query }}' required>
	  <button type="submit">Search</button>
	</form>
    <div  class="row">
        <h1 style="padding-left: 15px">Inventory Information</h1>
        <a href="{% url 'icsApp:import_data' %}" onclick="return confirm('Make sure to import a csv file')">
			<span class="btn btn-primary" style="float:right">Import</span></a>
        <a href="{% url 'icsApp:export_data' %}" onclick="return confirm('Data will be exported to a csv file')">
            <span class="btn btn-primary" style="float:right">Export</span></a>
    </div>
	<div>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr class="bg-info">
					<th style="white-space:nowrap;">
						Item Name
						<a href="{% url 'icsApp:ascending_item' %}" class='triangle-up'></a>
						<a href="{% url 'icsApp:descending_item' %}" class='triangle-down'></a>
					</th>
					<th>Quantity</th>
					<th>Location</th>
					<th>Item Position</th>
					<th style="white-space:nowrap;">
						Category
						<a href="{% url 'icsApp:ascending_category' %}" class='triangle-up'></a>
						<a href="{% url 'icsApp:descending_category' %}" class='triangle-down'></a>
					</th>
					<th style="white-space:nowrap;">
						Vendor
						<a href="{% url 'icsApp:ascending_vendor' %}" class='triangle-up'></a>
						<a href="{% url 'icsApp:descending_vendor' %}" class='triangle-down'></a>
					</th>
					<th>Vendor ID</th>
					<th>Link</th>
					<th>Unit-price</th>
					<th>Updated Date</th>
					<th>Total Value</th>
					<th colspan="2">Actions</th>
				</tr>
			</thead>
			<tbody>
			{% for inventory in inventorys %}
                <tr>
					<td>{{ inventory.item_name }}</td>
                    <td class="row">{{ inventory.quantity }}
						<a href="{% url 'icsApp:quantity_increase' pk=inventory.pk %}"
                           class="rbutton">+</a>
						<a href="{% url 'icsApp:quantity_decrease' pk=inventory.pk %}"
                           class="rbutton">-</a>
					</td>
                    <td>{{ inventory.location }}</td>
                    <td>{{ inventory.item_position }}</td>
                    <td>{{ inventory.category }}</td>
                    <td>{{ inventory.vendor }}</td>
					<td>{{ inventory.vendor_id }}</td>
                    <td><a href={{ inventory.link }}>{{ inventory.link }}</a></td>
					<td>{{ inventory.unit_price }}</td>
					<td>{{ inventory.updated_date }}</td>
					<td>{{ inventory.total_values }}</td>
					<td><a href="{% url 'icsApp:inventory_edit' pk=inventory.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'icsApp:inventory_delete' pk=inventory.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}

			</tbody>
		</table>
        <div>
			<a href="{% url 'icsApp:inventory_new' %}" class="row"><span class="btn btn-primary">Add Item</span></a>
     	</div>
	</div>
    </div>
</body>
</html>

icsApp/templates/inventory_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Item</title>
</head>
<body>
    <h1>Add the new Inventory item details</h1>
    <form method="POST" class="inventory-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</body>
</html>